### ISSUE TITLE
Is the current autopush document describe right api?

### ISSUE THREAD

**Issue by zoumiaojiang** [mozilla-services/autopush#1163]
I' m trying the [Push Service Bridge HTTP Interface](https://autopush.readthedocs.io/en/latest/http.html#post--v1-type-app_id-registration) in my app, I hava given right `type` and `app_id`，but it's not work.

here is the URL

```
curl https://updates.push.services.mozilla.com/v1/fcm/{my_fcm_sender_id}/registration' --data-binary '{"token": "my_fcm_token_generated_by_sdk"}
```

but got this response:

```
{"code": 400, "errno": 108, "error": "Bad Request", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate Invalid router"}
```

**Comment by jrconlin** [comment]
The push service bridge is used by autopush to communicate with known, third party protocols. Currently, these are GCM and APNs, which are used for instances of firefox on mobile devices. These are not for public use, but are described so that people understand what our code does if they choose to audit it.

Fortunately, you don't need to use any of that in order to use Webpush. It's far simpler. 
If you want to use WebPush, I would suggest reading the documentation at https://developer.mozilla.org/docs/Web/API/Push_API.
