### ISSUE TITLE
Add delivery receipts

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#122]
Implementation plan:

- [ ] Create a separate receipt node that uses the Python 3.4 `nghttp2` binding.
- [ ] Store receipt node mappings in the `router` table.
- [ ] Extend the `register` WebSocket message to return the "receipt subscribe" endpoint.
- [ ] Add a `ReceiptSubscribeHandler` that returns the "receipt subscription" endpoint in the response. The token for this endpoint is `{uaid}:{chid}:{receiptId}`.
- [ ] Add `Push-Receipt` header handling to the `EndpointHandler`.

How this fits together:

1. The receipt node exposes an internal handler that receives acks from the connection node, and a public handler (the "receipt subscription" endpoint) for app servers. When the app server connects to the receipt handler, we store the node mapping in DynamoDB.
2. When an app server requests receipts via the `Push-Receipt` header, extract the token from the receipt URL, then verify that the `uaid` and `chid` match. The "version" becomes `{messageId}:{receiptId}`. (It's opaque to the client either way; the version for messages without receipts will just be `{messageId}`).
3. When the client acks a message with a receipt, find the home receipt node for the `receiptId`, then send a request to the internal handler.
4. The receipt node receives the request, checks if the app server is connected, then wraps the ack in a push promise and sends it back to the app server.

All in all, this is symmetrical to how we handle clients. Reliability of acks is still under discussion; for now, let's assume best-effort, so that we don't have to store acks. :stuck_out_tongue_winking_eye:

**Comment by kitcambridge** [comment]
@bbangert, @jrconlin Pennies for your thoughts? These verbose issues are my attempt at being more vocal. :wink:

**Comment by bbangert** [comment]
Step 1: Sounds good!

Step 2: I'm not sure why a receipt node mapping needs to be stored in the router table. The receipt subscription needs to be stored on the notification itself, since each notification could have a different app-server with a different receipt subscription. If you're referring to the fact that the receipt subscription that a appserver creates needs to setup the mapping for it to get notifications, yup, makes sense. In theory the flexibility of full-data notifications I added for WebPush should be fine for it.

Step 3: Yup, the "receipt subscribe" endpoint should probably be the nghttp2 node itself.

Step 4: Sounds Good.

Step 5: Sounds Good.

I think that's a fairly good plan.

Since this code is going to be using a fully different Python interpreter, there's no nice way to have it live in the same package. So it will need to be in a new package, maybe "push-h2" (to reflect that when we add webpush h2 for clients, it also goes in there)? I'm not great at naming, and this doesn't use autobahn, so no need to use autopush as a name.

For the client ack'ing a message, that's the only somewhat hairy point. Because in theory it becomes almost like a p2p message.... and ideally the autopush node would directly route it to the h2 node if the appserver is connected.... we should probably discuss that part in person. Great summary of the steps!

**Comment by jrconlin** [comment]
I do like the idea of treating receipts as push messages, so I get the idea of storing the mapping in the router table.Unfortunately, I think that having effectively different end points and other code complicates things right now. Probably not as much a cost savings. It does feel a bit like we're duplicating a lot of things, though.

**Comment by bbangert** [comment]
Removing for now as we have no immediate plans to implement this until the DOM API includes the receipt URL.
