### ISSUE TITLE
SHA256 UAID in database

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autopush#228]
UAIDs and CHIDs don't need to be stored in cleartext, since user agents and notifications resubmit them. It would be preferrable to store them hashed in database, and only do comparisons with what a user agent submits. This would prevent a database leak from revealing them.

**Comment by bbangert** [comment]
bcypt is CPU intensive, isn't it? Why not SHA512 or something?

**Comment by jrconlin** [comment]
We seem to have this discussion frequently. The UAID is a nonce that's a proxy for the User. Likewise, the CHID is a nonce for the app that is requesting data (not the generator for the channel since each is unique, just that there is a channel). If the database is compromised, you can find out that a UAID has a number of channels.

In order to generate an endpoint, you need the opaquing key, which is not stored in the database. 

And the keys for the data encryption don't even pass through our system, so that's going to be rather difficult. 

The server can trigger the client to regenerate it's UAID by invalidating it and forcing the client to re-register UAIDs, which is mostly invisible to the end user (aside from some message loss between the last access and when the client regenerates and distributes the new endpoints. There may be some value to the server sending a polite "You might want to spin the locks on your UAID" if we think that a given UAID might be compromised, but @kitcambridge has told me that the hard bounce is potentially cleaner.

What security are we gaining by further obscuring an effective nonce?

**Comment by jvehent** [comment]
@bbangert: Mostly because of crypto details: [bcrypt is better](http://security.stackexchange.com/questions/5153/is-there-any-advantage-of-bcrypt-over-multiple-iterations-of-sha-x-md5) at storing secret hashes than the alternatives. As of cost, on my laptop, a single bcrypt operation takes ~80 milliseconds ([test code](https://gist.github.com/cde742d6c769736d3337))

@jrconlin: Leaked UAIDs can be used to tamper with notifications by impersonating a user agent and deleting notifications and channels. Hashing them in database is an easy way to prevent this, and make the database less sensitive.

**Comment by bbangert** [comment]
@jvehent and I discussed this. Due to some DoS concerns, a SHA256 is sufficient in this case.
