### ISSUE TITLE
Use 410 Gone instead of 404 Not Found

### ISSUE THREAD

**Issue by callahad** [mozilla-services/autopush#312]
Per [RFC 7231](http://tools.ietf.org/html/rfc7231), [404 Not Found](http://tools.ietf.org/html/rfc7231#section-6.5.4) "does not indicate whether this lack of representation is temporary or permanent; the 410 (Gone) status code is preferred over 404 if the origin server knows, presumably through some configurable means, that the condition is likely to be permanent."

As far as I can tell, everything we return 404 for is indeed permanent. Perhaps we should switch to [410 Gone](http://tools.ietf.org/html/rfc7231#section-6.5.9), which "indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent. [...] The 410 response is primarily intended to assist the task of web maintenance by notifying the recipient that the resource is intentionally unavailable and that the server owners desire that remote links to that resource be removed."

**Comment by kitcambridge** [comment]
This is a good point. We could definitely return a 410 for error code 103 (valid endpoint token, but the user agent ID isn't in the database) and 106 (subscription ID not in database—though, since the endpoint token is valid, the subscription existed at one time). 102 (invalid endpoint token) should probably be a 400.
