### ISSUE TITLE
Fix bug with version defaulting to 0

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#395]
cyclone defaults to None being passed in for missing params, this should be accounted for in the handlers.

**Comment by jrconlin** [comment]
In addition: there needs to be testing to ensure that the UAID and CHID being provided are not being corrupted before being referenced by storage. 

We had a problem where '123' was being corrupted into a valid UUID like entity in some tests this produced false positive testing instead of flagging the value as being incorrect.
