### ISSUE TITLE
Make storage/router DynamoDB table names configurable

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#4]
The router/storage table names used must be configurable, as 'router' and 'storage' could cause name conflicts.

**Comment by jrconlin** [comment]
good point. We should call them 'test' and 'example'.

**Comment by bbangert** [comment]
Oh, guess the region should also be configurable.

**Comment by jrconlin** [comment]
Yeah, and provisioning. My rule of thumb is that any setting we use to connect to something else goes into a config file. Likewise, any local that would be handy for ops to use to diagnose or extinguish fires also goes into a config.

**Comment by bbangert** [comment]
I was thinking provisioning. But I'm not sure its great for each node in the cluster to be looking at that and tweaking it as needed. Would be better to have ops manage the provisioning throughput of the table in their own manner (manually if needed).

**Comment by jrconlin** [comment]
Ah, but I'm not sure how the app might pick up whatever modification. As I understand, ops tends to run these sorts of things via puppet or similar config systems. (heh, zookeeper?) so they'd tweak the config in one location and then deploy as needed. I tend to favor having more knobs than I probably need, since I've been in the position of trying to fix stuff that's suddenly broken and used a hard-coded value at previous jobs. Perfectly fine with someone else suggesting a better solution.

**Comment by bbangert** [comment]
I suppose I was trying to avoid the case where ops needs to redeploy a server just to change the provisioning, when they could change it via the AWS web UI to meet temporary throughput needs.
