### ISSUE TITLE
Refactor object initializers

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#632]
We have multiple, large, hideous object initializers. I.e. AutopushSettings, PushState, etc.

Refactor should use attrs:
https://glyph.twistedmatrix.com/2016/08/attrs.html
https://attrs.readthedocs.io/en/stable/index.html

**Comment by pjenvey** [comment]
* make_settings should move to Settings.from_argparse, and hopefully some of the attr's validation can aid in cleaning it up
* Settings' constructor defaults should really sync up w/ argparse defaults in some fashion
* Likely rename AutopushSettings -> AutopushConfig because referring to it as "ap_settings" in handlers (to not clash w/ cyclone's "settings") is slightly annoying
* extra credit: separation of connection/endpoint settings
