### ISSUE TITLE
Move to APNs http/2 API

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#662]
The old API is incredibly bad. Apple recommends "All developers should migrate their remote notification provider servers to the more capable and more efficient HTTP/2-based API".

How apns.py and our apnsrouter.py have to handle the retry logic is particularly bad and probably not all that scalable. We don't even utilize its silly feedback server for potential retries.

The new HTTP/2 API should improve this. However I'm not sure there's a reliable enough python lib out there yet to switch to..

**Comment by jrconlin** [comment]
honestly? I'd prefer to use HTTP2. There was some discussion earlier about using SNS to effectively wrap the APNs calls, but that introduces its own level of overhead and complexity. (Same with FCM for what it's worth.) There's a weird cottage industry of having other things deal with APNs, mostly because all of the hassle around trying to send messages to them.

It may be time for me to renew my Apple Dev license and just write a new APNs library.

**Comment by kitcambridge** [comment]
Connections to the old API can also [wedge](https://github.com/Voxer/node-apn/commit/527a68de33087ca548dbce20f7ccf0b7394ffb25#commitcomment-9610565).

**Comment by jrconlin** [comment]
That's... Sigh...
