### ISSUE TITLE
Add profiling reports to tests

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#749]
Our unit/integration tests should include some profiling tests to track worst/best-case scenarios for common client commands via the websocket, and common/uncommon paths for the endpoint.

Some first targets:

- Validation timing for various request types, with/without VAPID
- Time to execute websocket commands

**Comment by pjenvey** [comment]
I think in general we'll get more traction from enhancing benchmarks in ap-loadtester, since we'll soon be tracking its results over time

however it would definitely be useful right now to see profiling comparing with vs without VAPID from test_integration

I'm not sure how useful websocket timings from it would be at the moment. it'd really only be for profiling done locally -- the travis environment isn't reliable enough for getting anything from profiling results ran on it

**Comment by bbangert** [comment]
Per @pjenvey, we are moving to tracking memory use and performance with metrics used from deployments, rather than in unit tests.
