### ISSUE TITLE
errno: 106, No such subscription.

### ISSUE THREAD

**Issue by devqualwebs** [mozilla-services/autopush#776]
Initally we are using curl to send push notification using this curl,
curl -I -X POST --header "ttl: 60" "https://updates.push.services.mozilla.com/wpush/v1/REST-OF-ENDPOINT" which was working correctly. From some days it started throwing error like {"errno": 106, "message": "No such subscription", "code": 410, "more_info": "http://autopush.readthedocs
.io/en/latest/http.html#error-codes", "error": ""}.

But from doc, It's not very clear why running code stopped working and how to solve it.

**Comment by bbangert** [comment]
We return a 410 when the WebPush URL was at one time valid, but is no longer valid (and will never be valid again). This happens when a user-agent hasn't connect to our system recently enough (within 60 days) or has unsubscribed for any reason (user manually unsubscribed, too many messages, reset user profile).

You should cease any further delivery attempts to a 410 and remove the URL as a valid WebPush subscription. If you believe the user has accidentally unsubscribed and have their email, one possible remedy would be to confirm via email that they meant to unsubscribe or provide a link back to your website so that they may be asked again to subscribe.

**Comment by devqualwebs** [comment]
Thanks bbangert for your response. We get issue here. But now problem here is that on sending notification, Browser is receiving notification and showing activity in about:debugging#workers panel. But no code is running in push scope we had registered in service worker as shown below.

`self.addEventListener('push', function(event)
{
     var notification = new Notification('Notification title', {
      icon: 'http://cdn.sstatic.net/stackexchange/img/logos/so/so-icon.png',
      body: "Hey there! You've been notified!",
    });

    notification.onclick = function () {
      window.open("http://stackoverflow.com");      
    };
});`

**Comment by bbangert** [comment]
This is not a general Javascript help forum, you might want to try one of those with people familiar with using Push and service workers.

**Comment by kitcambridge** [comment]
@devqualwebs In the future, Stack Overflow or [IRC](https://wiki.mozilla.org/IRC) are better for service worker-related questions, but I'll just respond here. 😄

The problem is `new Notification(...)` isn't available in service workers, so your `push` event handler will throw an exception. I think you'll see the error if you're developing locally in Firefox, and open the Dev Tools Web Console. After a while, Firefox sees your `push` event hasn't shown any notifications, and drops your subscription. That's why you get a 410 when you try to send.

In a service worker, you can use `self.registration.showNotification` and the `notificationclick` event instead, like so:

```js
self.addEventListener('push', function(event) {
  event.waitUntil(self.registration.showNotification('Notification title', {
    icon: 'http://cdn.sstatic.net/stackexchange/img/logos/so/so-icon.png',
    body: "Hey there! You've been notified!",
  }));
});

self.addEventListener('notificationclick', function(event) {
  event.waitUntil(self.clients.openWindow("http://stackoverflow.com"));
});
```

Check out the [Push Clients](https://serviceworke.rs/push-clients.html) demo on the Service Worker Cookbook.
