### ISSUE TITLE
Web Push form Firefox Mobile

### ISSUE THREAD

**Issue by bjjclimbin** [mozilla-services/autopush#843]
Hello.

I have been implementing web push notifications through my portal. The application works great for firefox Desktop and other browsers (such as chrome desktop and mobile) but when i try to push notifications to a mobile user, the server's response is {"code": 410, "errno": 105, "error": "", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate Critical Failure: Client is unreachable due to a configuration error. Unable to send message."} . I have tried several different methods to push notifications even paid service providers and the notifications do not arrive on the mobile devices (firefox permissions have been set correctly) .

**Comment by jrconlin** [comment]
Hi, I presume that you're talking about a portal that you're running yourself (our logs aren't showing a 410:105 error in the past day or so). 

If you are running your own instance of autopush on your own server, then you'll need to configure the various external bridges yourself. The [shared configuration file](https://github.com/mozilla-services/autopush/blob/master/configs/autopush_shared.ini.sample#L86) has information about what you need to set up, Each bridge acts as it's own GCM app, so you'll need to configure a senderID (with associated keys and permissions).

Be aware that bridges are a proprietary extension for autopush. This means that you will need to modify the Firefox mobile client to include the corresponding credentials as well.  While you're free to experiment with this interface, it's not officially supported for third party use. The code is obviously available and is commented, but unfortunately, we don't really have the available resources to help you navigate all the hurdles. (Obviously, we'd LOVE if you would publish any notes or comments about your experience so that others can benefit!)

**Comment by kitcambridge** [comment]
Could you also paste the endpoint, please?

**Comment by bjjclimbin** [comment]
Hello.

This is one of the endpoints i have been trying.

https://updates.push.services.mozilla.com/wpush/v2/gAAAAABYwtR-
Bz7ldT4XuZSZ3vBAI83cefC1s7vCk9VPRoUSjhOn6VsUPmN5rx0-_
fF42XllPznMIZGwMgpR80jAsOpBW-sMiYM3G41JUDpkp4hSEOR3SGdBSl0Q
7Tiz9A8kXOfvFFif821fAwUYrGgOYI0Nib51xdHt46Aa2U4mHrY6lRq-hFs" --request POST
--header "TTL: 60" --header "Content-Length: 0" --header "Authorization:
WebPush eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiJodHRwczovL3VwZGF0ZX
MucHVzaC5zZXJ2aWNlcy5tb3ppbGxhLmNvbSIsImV4cCI6MTQ4OTUyMjAzMi
wic3ViIjoibWFpbHRvOnNpbXBsZS1wdXNoLWRlbW9AZ2F1bnRmYWNlLmNvLnVrIn0.
CXmt1sQd5H4yb8VZAXYw4PifL5glf8N-Ao_mBgNfq8QvKFsI4T5i3SmT6UgDrQAw7GX0G7IbInYcX82o7Kc_Ng"
--header "Crypto-Key: p256ecdsa=BDd3_hVL9fZi9Ybo2UUzA284WG5FZR30_
95YeZJsiApwXKpNcF1rRPF3foIiBHXRdJI2Qhumhf6_LFTeZaNndIo

Regards,

Luis

**Comment by jrconlin** [comment]
Thanks! Having this detail is a huge help.

I'm not sure why it's not showing up in our logs, but I was able to duplicate what you're seeing. It's an unusual response, but it might be an older bug cropping up again. If I may ask, is this an older mobile device that has been running firefox for quite some time? We had a problem with some devices registering with an incorrect ID right when WebPush was made available (about July of last year). Unfortunately, the only "fix" is to completely uninstall firefox, and then re-install it. I can fill you in on the gory details of why if you like, but you probably don't need to know them.

 Oddly, the source of the message is GCM. GCM is returning to our bridge "Client is unreachable due to a configuration error." when we attempt to send. I'm able to use [a simple test page](https://jrconlin.github.io/Webpush_QA/) to verify that we can send to android devices. I would guess that page would also fail for the device you're trying to connect to.

**Comment by jrconlin** [comment]
After talking with someone over here, this may indeed be a bug in autopush, THANK YOU! 

In short, what may be happening is if a given UAID is determined to be a 410 for various reasons, we indicate that to the subscription provider. The client may not realize this, however and may not re-register. The folks working on gecko have asked for a method to use to have the client check it's state (#844). which may help resolve this problem, but it will take a bit to roll out.

For now, marking this as a dup of #844.

**Comment by bjjclimbin** [comment]
Hello.

Thanks a lot for the information, i will be following the issue with big
attention. If there is something i can do in order to help you fix the
issue please let me know

Best regards,

Luis

2017-03-15 2:19 GMT+01:00 JR Conlin <notifications@github.com>:

**Comment by jrconlin** [comment]
resolved with #847
