### ISSUE TITLE
Track down memory change issue in autoendpoint in 1.28.0

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#917]
Starting with 1.28.0 release, autoendpoint's memory usage has skyrocketed. We need to track down and fix the memory issue as it causes issues with the log shipper when the memory is severely impacted.

**Comment by pjenvey** [comment]
Also #802

The likeliest culprit that changed in 1.28.0 was #854, which switched our VAPID verification from pycrypto to cryptography

**Comment by alex** [comment]
FWIW, in the meantime you can probably add some semi-targetted `__pypy__.add_memory_pressure` yourself to improve the situation. Anywhere in `VerifyJWT.decode` with a value of 128 will probably have a noticable impact.

**Comment by pjenvey** [comment]
this isn't quite tracked down yet

**Comment by bbangert** [comment]
What are the specific criteria for closing this?

**Comment by pjenvey** [comment]
See #802: Our slow leaks are due to likely fragmentation: pypy's memory allocation on top of glibc malloc can cause this slow leak. A MALLOC_ARENA_MAX=2 has helped the endpoint nodes a lot, further experimentation w/ jemalloc is needed, tracked in: https://github.com/mozilla-services/push-service/issues/79 and https://bugzilla.mozilla.org/show_bug.cgi?id=1442705
